-- ============================================================
-- WormOS - Hyprland Configuration
-- Based on the original autogenerated Hyprland Lua config
-- and matched to the original WormOS hyprland.conf
-- ============================================================

------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "alacritty"
local fileManager = "dolphin"
local menu        = "wofi --show drun -n"
local browser     = "brave"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar & hyprpaper")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "15")
hl.env("HYPRCURSOR_SIZE", "15")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 10,

        border_size = 1,

        col = {
            active_border = {
                colors = {
                    "rgba(ffffffee)",
                    "rgba(ffffffee)",
                },
                angle = 45,
            },

            inactive_border = "rgba(20133eaa)",
        },

        resize_on_border = false,
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = 5,

        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = 0xee1a1a1a,
        },

        blur = {
            enabled = false,
            size = 3,
            passes = 1,
            ignore_opacity = true,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

------------------------------
---- ANIMATION CURVES --------
------------------------------

hl.curve("easeOutQuint", {
    type = "bezier",
    points = {
        {0.23, 1},
        {0.32, 1},
    },
})

hl.curve("easeInOutCubic", {
    type = "bezier",
    points = {
        {0.65, 0.05},
        {0.36, 1},
    },
})

hl.curve("linear", {
    type = "bezier",
    points = {
        {0, 0},
        {1, 1},
    },
})

hl.curve("almostLinear", {
    type = "bezier",
    points = {
        {0.5, 0.5},
        {0.75, 1},
    },
})

hl.curve("quick", {
    type = "bezier",
    points = {
        {0.15, 0},
        {0.1, 1},
    },
})

---------------------
---- ANIMATIONS -----
---------------------

hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})

hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})

hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})

hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})

hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

----------------------------
---- DWINDLE LAYOUT --------
----------------------------

-- pseudotile is no longer a valid dwindle config option.
-- SUPER + P below still provides pseudotiling.

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

----------------------------
---- MASTER LAYOUT ---------
----------------------------

hl.config({
    master = {
        new_status = "master",
    },
})

----------------
---- MISC ------
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
    },
})

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",

        follow_mouse = 1,

        sensitivity = 0,

        touchpad = {
            natural_scroll = false,
        },
    },
})

------------------
---- GESTURES ----
------------------

-- Original config:
-- gestures {
--     workspace_swipe = false
-- }
--
-- No workspace swipe gesture is configured.


---------------------
---- PER-DEVICE -----
---------------------

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

---------------------------
---- APPLICATIONS ---------
---------------------------

-- SUPER + Q
hl.bind(
    mainMod .. " + Q",
    hl.dsp.exec_cmd(terminal)
)

-- SUPER + C
hl.bind(
    mainMod .. " + C",
    hl.dsp.window.close()
)

-- SUPER + B
hl.bind(
    mainMod .. " + B",
    hl.dsp.exec_cmd(browser)
)

-- SUPER + M
hl.bind(
    mainMod .. " + M",
    hl.dsp.exec_cmd("hyprctl dispatch exit")
)

-- SUPER + E
hl.bind(
    mainMod .. " + E",
    hl.dsp.exec_cmd(fileManager)
)

-- SUPER + V
hl.bind(
    mainMod .. " + V",
    hl.dsp.window.float({
        action = "toggle",
    })
)

-- SUPER + R
hl.bind(
    mainMod .. " + R",
    hl.dsp.exec_cmd(menu)
)

-- SUPER + P
-- Toggle pseudotiling
hl.bind(
    mainMod .. " + P",
    hl.dsp.window.pseudo()
)

-- SUPER + J
-- Toggle Dwindle split direction
hl.bind(
    mainMod .. " + J",
    hl.dsp.layout("togglesplit")
)

--------------------
---- SCREENSHOT ----
--------------------

-- Print Screen
hl.bind(
    "Print",
    hl.dsp.exec_cmd(
        'grim -g "$(slurp -d)" - | wl-copy'
    )
)

-------------------------
---- WINDOW FOCUS -------
-------------------------

-- SUPER + SHIFT + LEFT
hl.bind(
    mainMod .. " + SHIFT + left",
    hl.dsp.focus({
        direction = "left",
    })
)

-- SUPER + SHIFT + RIGHT
hl.bind(
    mainMod .. " + SHIFT + right",
    hl.dsp.focus({
        direction = "right",
    })
)

-- SUPER + SHIFT + UP
hl.bind(
    mainMod .. " + SHIFT + up",
    hl.dsp.focus({
        direction = "up",
    })
)

-- SUPER + SHIFT + DOWN
hl.bind(
    mainMod .. " + SHIFT + down",
    hl.dsp.focus({
        direction = "down",
    })
)

-----------------------
---- WORKSPACES -------
-----------------------

for i = 1, 10 do

    -- Workspace 10 uses key 0
    local key = i % 10

    -- SUPER + [0-9]
    hl.bind(
        mainMod .. " + " .. key,
        hl.dsp.focus({
            workspace = i,
        })
    )

    -- SUPER + SHIFT + [0-9]
    hl.bind(
        mainMod .. " + SHIFT + " .. key,
        hl.dsp.window.move({
            workspace = i,
        })
    )
end

---------------------------
---- SPECIAL WORKSPACE ----
---------------------------

-- SUPER + S
hl.bind(
    mainMod .. " + S",
    hl.dsp.workspace.toggle_special("magic")
)

-- SUPER + SHIFT + S
hl.bind(
    mainMod .. " + SHIFT + S",
    hl.dsp.window.move({
        workspace = "special:magic",
    })
)

-------------------------------
---- EXISTING WORKSPACE SCROLL
-------------------------------

-- SUPER + RIGHT
hl.bind(
    mainMod .. " + right",
    hl.dsp.focus({
        workspace = "e+1",
    })
)

-- SUPER + LEFT
hl.bind(
    mainMod .. " + left",
    hl.dsp.focus({
        workspace = "e-1",
    })
)

------------------------------
---- MOVE / RESIZE WINDOWS ---
------------------------------

-- SUPER + Left Mouse Button
hl.bind(
    mainMod .. " + mouse:272",
    hl.dsp.window.drag(),
    {
        mouse = true,
    }
)

-- SUPER + Right Mouse Button
hl.bind(
    mainMod .. " + mouse:273",
    hl.dsp.window.resize(),
    {
        mouse = true,
    }
)

---------------------------------
---- AUDIO / BRIGHTNESS KEYS ----
---------------------------------

-- Volume Up
hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(
        "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
    ),
    {
        locked = true,
        repeating = true,
    }
)

-- Volume Down
hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd(
        "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
    ),
    {
        locked = true,
        repeating = true,
    }
)

-- Mute
hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd(
        "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    ),
    {
        locked = true,
        repeating = true,
    }
)

-- Microphone Mute
hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd(
        "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
    ),
    {
        locked = true,
        repeating = true,
    }
)

----------------
-- BRIGHTNESS --
----------------

-- Brightness Up
hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd(
        "brightnessctl s 10%+"
    ),
    {
        locked = true,
        repeating = true,
    }
)

-- Brightness Down
hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd(
        "brightnessctl s 10%-"
    ),
    {
        locked = true,
        repeating = true,
    }
)

--------------------
---- MEDIA KEYS ----
--------------------

-- Next Track
hl.bind(
    "XF86AudioNext",
    hl.dsp.exec_cmd("playerctl next"),
    {
        locked = true,
    }
)

-- Pause
hl.bind(
    "XF86AudioPause",
    hl.dsp.exec_cmd("playerctl play-pause"),
    {
        locked = true,
    }
)

-- Play
hl.bind(
    "XF86AudioPlay",
    hl.dsp.exec_cmd("playerctl play-pause"),
    {
        locked = true,
    }
)

-- Previous Track
hl.bind(
    "XF86AudioPrev",
    hl.dsp.exec_cmd("playerctl previous"),
    {
        locked = true,
    }
)

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Ignore maximize requests
hl.window_rule({
    name = "suppress-maximize-events",

    match = {
        class = ".*",
    },

    suppress_event = "maximize",
})

--------------------------------
---- XWAYLAND DRAG FIX ---------
--------------------------------

hl.window_rule({
    name = "fix-xwayland-drags",

    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },

    no_focus = true,
})